#!/usr/bin/env python3
"""Rebuild our test outputs."""

from pathlib import Path

from svgmapper.services.creator import Creator


def _build_examples(here: Path) -> None:
    examples = here.parent / "examples"
    svgdir = examples / "svg"
    typstdir = examples / "typst"
    pdfdir = examples / "pdf"
    for dr in (svgdir, pdfdir):
        dr.mkdir(exist_ok=True)
    for fn in examples.glob("*.svgmap"):
        st = fn.stem
        svg = svgdir / f"{st}.svg"
        typ = typstdir / f"{st}.typ"
        pdf = pdfdir / f"{st}.pdf"
        creator = Creator(inp=fn, output=svg, typst=typ, pdf=pdf)
        creator.create()


def main() -> None:
    """Rebuild the test outputs."""
    here = Path(__file__).parent
    _build_examples(here)


if __name__ == "__main__":
    main()
