#!/usr/bin/env python3
"""Rebuild our test outputs."""

from pathlib import Path

from svgmapper.services.converter import Converter
from svgmapper.services.creator import Creator


def _build_tests(data: Path, output: Path) -> None:
    # Recreate crypt.svg from crypt.desc

    converter = Converter(
        inp=(data / "crypt.desc"), output=(output / "crypt.svgmap")
    )
    converter.convert_input()

    # Crypt from svgmap

    creator = Creator(
        inp=(output / "crypt.svgmap"),
        output=(output / "crypt-alt-settings.svg"),
        settings=data / "settings.json",
    )
    creator.create()

    creator = Creator(
        inp=(output / "crypt.svgmap"), output=(output / "crypt.svg")
    )
    creator.create()

    # Support files
    fns = ("crinkle", "elements")

    for fn in fns:
        creator = Creator(
            inp=data / f"{fn}.svgmap", output=output / f"{fn}.svg"
        )
        creator.create()


def _build_examples(here: Path) -> None:
    examples = here.parent / "examples"
    svg = examples / "svg"
    svg.mkdir(exist_ok=True)
    for fn in ("entry", "caves", "crypt"):
        creator = Creator(
            inp=examples / f"{fn}.svgmap", output=svg / f"{fn}.svg"
        )
        creator.create()


def main() -> None:
    """Rebuild the test outputs."""
    here = Path(__file__).parent
    data = here.parent / "tests" / "data"
    output = data / "output"

    _build_tests(data, output)
    _build_examples(here)


if __name__ == "__main__":
    main()
